source 'https://rubygems.org'

gem 'rack'
gem 'rake'
gem 'rack-test'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'ruby-oci8'
gem 'ruby-plsql'
gem 'bootstrap-sass', '3.3.7'
gem 'sinatra-flash'
gem 'rack-flash3'
